version: '2'
services:
  grafana:
    build: ./grafana
    ports:
    - 3000:3000/tcp
    environment:
    - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
  nodered:
    build: nodered
    ports:
    - 1880:1880/tcp
  influxdb:
    image: influxdb
    volumes:
    - /var/lib/influxdb
    ports:
    - 8086:8086/tcp
    environment:
    - INFLUXDB_DB=masterUC
  mosquitto:
    image: toke/mosquitto
    ports:
    - 1883:1883/tcp
    - 9001:9001/tcp
  freeboard:
    build: ./freeboard
    ports:
    - 8080:8080/tcp
  replaygpx:
    build: ./replaygpx
    environment:
    - MQTT_BROKER=mqtt://mosquitto
    - DEVICEID=vehicle1
