version: '2'
services:
  grafana:
    build: ./grafana
    ports:
    - 3000:3000/tcp
    environment:
    - GF_INSTALL_PLUGINS=grafana-piechart-panel
  nodered:
    image: nodered/node-red-docker
    ports:
    - 1880:1880/tcp
  influxdb:
    image: influxdb
    volumes:
    - /var/lib/influxdb
    ports:
    - 8086:8086/tcp
