version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000/tcp
  nodered:
    image: nodered/node-red-docker
    ports:
    - 1880:1880/tcp
  influxdb:
    image: influxdb
    volumes:
    - /var/lib/influxdb
    ports:
    - 8086:8086/tcp
